import '@/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import { Noto_Color_Emoji } from 'next/font/google';

import { Toaster } from '@/components/ui/toaster';
import { TRPCReactProvider } from '@/trpc/react';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const emoji = Noto_Color_Emoji({
  weight: '400',
  display: 'swap',
  subsets: ['emoji'],
  preload: true,
  variable: '--font-emoji',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html
        lang='en'
        className={`${GeistSans.variable} ${emoji.variable} font-sans antialiased`}
      >
        <body>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
